FROM node:18.12.0

USER root

WORKDIR /usr/src/app
COPY api/package*.json ./

RUN npm install

COPY ./api . 

# ENTRYPOINT [ "/bin/bash" ]
# CMD [ "npm", "run", "build" ]
EXPOSE 3000
CMD [ "npm", "run", "start:api:dev" ]
# CMD [ "node", "./dist/api/src/app.js" ]
# CMD [ "node", "server.js" ]
# CMD [ "ts-node", "api/src/app.ts" ]